### ISSUE TITLE
Badge Requesting! ~ Important: Please read before submitting your request

### ISSUE THREAD

**Issue by PixelBreeze** [TheBanHammer/nc-themes#1]
# Submitting a Badge request.
## Important Requirements
1. When you send us a badge request you need to provide the image you wish to be as displayed as the badge.
2. The image size must be even starting from 30x30 pixels. For example: 50x50 pixels, 100x100 pixels etc.
3. If you do not have a photo editing program and cant resize it, send us the image here you have made/found and in the **Extra information** area state what you want us to do with the image. For example, what part you want from the image to be the badge, if you want any borders around it or change some colors.
4. **NEW** - No gifs.
## Example:
- **Your Username**: PixelBreeze 
  ( _It's Recommended to write the username that you are best know as in the community and not your current plug.dj username_ )
- **Your Plug.dj ID**:  196490 
  ( _Your Plug.dj ID can be found next to your name if you are using for example RCS and have it enabled. Other option is to press F12 and open the console while Plug.dj room tab is open and by typing **API.getUser().id** into the console. The numbers displayed below will be your ID_ )
- **Image Link or attachment**: http://imgur.com/d4njTCy 
  ( _If you used an attachment just say attachment below or something so we know_ )
- **Extra Information**: I want a gold border around my badge please. ( _Your extra info here_ )
## Badge Request Template:
1. **Your Username**:
2. **Your Plug.dj ID**:
3. **Image Link or attachment**:
4. **Extra Information**:

**If you have any other questions about this, contact PixelBreeze or TheBanHammer on Skype, on the Plug.dj room or Discord.**

**!!! Note that this feature is for staff only so if you are not staff you cannot get a custom badge! Exceptions are possible if they are approved by our room's managers.**

**Comment by Xfirenl** [comment]
Xfirenl
5483545
http://i.imgur.com/hnB5Nbl.png
**DONE ~Pixel**

**Comment by Tracelda** [comment]
Cyan
3432506
http://imgur.com/AlalAFR 
Extra info:
Could i have a pink border (one similar to the pink in the image if possible)
**DONE ~Pixel**

**Comment by ghost** [comment]
Minymind
6355338
http://imgur.com/vsvxEUp
Ty in advanced :D 
**DONE ~Pixel**

**Comment by Lordenz** [comment]
Fabbes Hund
6116330
http://imgur.com/iPTuutM
**DONE ~Pixel** (Not implemented?)

**Comment by EmilydeLaValliere** [comment]
Emily de La Valliere
13443391
https://imgur.com/0ttxhTV (300x300 so should be easy to rescale if necessary)
Ty <3

**Comment by Pro-hop** [comment]
Pro Hop
7132658
http://imgur.com/GjqDDCU (Changed it so its actually visible :P)
Tyvm
**DONE ~Pixel**

**Comment by DavinhDang** [comment]
Your Username: Illyasviel von Einzbern
Your Plug.dj ID: 3893149
Image Link or attachment: http://imgur.com/T6hE4yo
Extra Information: Could you please add a purplish border I guess C;?

Thank you very much!

**Comment by BakaCow** [comment]
AdorableCow
4115530
http://imgur.com/a/5ZYo3
30 by 30
 Cows shall rule the world. 
**DONE ~Pixel**

**Comment by NightcoreBrianna** [comment]
Nightcore Brianna DJ 
Plug.DJ name - Neko-Berry
13442611
http://imgur.com/fNNLxPF
Extra Information: Could you please add a gold border around my badge please! <3 

Thank You! 

**DONE ~Pixel**

**Comment by Zrathex** [comment]
You Username: Zrathex
Plug.dj ID: 6328419
Image: http://img12.deviantart.net/6a55/i/2011/144/a/6/hatsune_miku_wallpaper__05___by_xian9142-d3h3jdc.jpg
Extra Information: Could you add a blue border around it? Also make it smaller cause I got no time lol!

**Comment by Gold-Solox** [comment]
1. Nue Houjuu
2. 3927729
3. http://i.picresize.com/images/2016/08/14/YGy8A.png
4. Nothing.
   **DONE**

**Comment by Zrathex** [comment]
Yes please.

**Comment by TheBanHammer** [comment]
@Zrathex read the requirements. Also that will look so bad in a small logo. Remember this has to be resized down to a tiny scale.

**Comment by l96alex** [comment]
@PixelBreeze Hi there, have you seen this dogeosaur?

**Comment by Zrathex** [comment]
@TheBanHammer http://image.prntscr.com/image/e886aacea5474326931cb49018a1a66c.png
How about this one? huh XD

**Comment by Joe2648** [comment]
Your Username: Joe2648
Your Plug.dj ID: 5386736
Image Link or attachment: 
![anime me 3](https://cloud.githubusercontent.com/assets/21124290/17809374/15c41ade-65e4-11e6-912f-608ca0d526c2.png)

Extra Information: ---------
**DONE**

**Comment by bulzaiguard** [comment]
Plug.DJ name - bulzai_guard
Your Plug.dj ID: 8067032
http://imgur.com/xV0HAgS
if gif is possible please this https://gyazo.com/ab47bd2090eac7645767208b1e20ec10
preview:
![cropped 50x50](https://cloud.githubusercontent.com/assets/15656233/19199083/84ebc5d8-8cc2-11e6-9da0-fd0c593cc03a.jpg)

Extra Information: .....

----- just changed picture ------

**Comment by Mrcl1450** [comment]
Mrcl-
13585808
http://i.imgur.com/jQzNXiX.gif
Could you add a yellow border? Ty

**Comment by Degreee** [comment]
Plug.Dj name ~ Degreе 
Your Plug.Dj ID: 5591954
![nichijoint](https://cloud.githubusercontent.com/assets/22476753/18880590/0a538754-84e1-11e6-8158-ee8485fdb109.png)
-----extra info-----
please green border xd
**DONE**

**Comment by ImmortalSausage** [comment]
Immortal Sausage
5941277
https://s12.postimg.org/tx91893ml/mei2.gif
**No GIFs**

**Comment by ResidentDjs** [comment]
Username: Resident DJs
Plug.dj ID: 13439816
Image: https://s-media-cache-ak0.pinimg.com/564x/59/6e/73/596e730d367f661e66f58ac6982d9eb2.jpg
Extra Information: None, thank you <3
**DONE**

**Comment by skylarkblue1** [comment]
Username: skylarkblue1
Plug ID: 4337051
Image: https://s-media-cache-ak0.pinimg.com/564x/66/45/f0/6645f0e2e2737b5c9c16f04b1196e85c.jpg

Thank you ^.^
**DONE**

**Comment by MysterHik** [comment]
Username : MysterHik
Plug ID : 13553790
Image : http://i.imgur.com/Hl42hd0.gifv
Maybe blue border? ;)
That's all thank's! :D
**Denied: No GIFs. Please select a diffrent image.**

**Comment by MysterHik** [comment]
Username : MysterHik
Plug ID : 13553790
Image : http://i.imgur.com/fyVfOCn.jpg
If it is too tall, I can rescale it.

Maybe blue border? ;)
That's all thank's! :D

Sorry for the previous picture :X
**DONE**

**Comment by rokmarkos** [comment]
Username : Tofu :D , better known as just Tofu
ID : 15006213
img : in attachments, could you give me a purplish boarder that matches her hair?
![a49ca876595cc056f39c8336a51a0e61_480](https://cloud.githubusercontent.com/assets/22868731/19417504/1d7634a8-93af-11e6-9ca0-c0766d47a1fb.jpg)

**DONE**

**Comment by AZRv2** [comment]
Username : AZR
Plug ID : 15020104
Image : http://imgur.com/ECdDStB
Extra Info : None thanks 

**DONE**

**Comment by NcWaifu** [comment]
**Name;** Waifu331
**ID;** 13477373
**Img Link;** http://i.imgur.com/1NObjFx.png
**_Extra info;_** _Could you make a golden boarder around it please_

**Done ~ Pixel**

**Comment by Levi--G** [comment]
**Name;** AnimeDev
**ID;** 13446247
**Img;** http://animedev.azurewebsites.net/Plug/badge.jpg Or: http://animedev.azurewebsites.net/Plug/badge.png
(please keep this link as I tend to change stuff ;) )
**Extra info;** Can you do custom css around the image?
(box-shadow: 0px 0px 5px #5500ff; on .id-13446247 > .badge-box) If not I understand ;)

**Comment by PixelBreeze** [comment]
All further badge setting will be done by the bot on plug.dj with the command: `!setbadge url`
